
TestCases/chapter15/15.3/15.3.4/15.3.4.5/15.3.4.5-2-9.js
Failed to translate/run...
Traceback (most recent call last):
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/tests/ES5Conform.py", line 1399, in run_test_case
    result = e.eval(test)
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/evaljs.py", line 67, in eval
    self.execute(code)
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/evaljs.py", line 62, in execute
    exec code in self._context
  File "<string>", line 2, in <module>
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/base.py", line 780, in __call__
    return self.call(self.GlobalObject, args) # todo  value of this
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/base.py", line 1178, in call
    return Js(self.code(*args))
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/host/jseval.py", line 42, in Eval
    executor(py_code)
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/host/jseval.py", line 49, in executor
    exec code in globals()
  File "<string>", line 18, in <module>
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/base.py", line 812, in callprop
    return cand.call(self, args)
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/base.py", line 1178, in call
    return Js(self.code(*args))
  File "<string>", line 96, in PyJs_anonymous_1_
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/base.py", line 812, in callprop
    return cand.call(self, args)
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/base.py", line 1178, in call
    return Js(self.code(*args))
  File "<string>", line 7, in PyJs_testcase_1_
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/base.py", line 780, in __call__
    return self.call(self.GlobalObject, args) # todo  value of this
  File "/Users/PiotrDabkowski/PycharmProjects/Js2Py/js2py/base.py", line 1178, in call
    return Js(self.code(*args))
TypeError: PyJsLvalInline() takes exactly 2 arguments (4 given)


{'not_implemented': 415, 'wrong': 178, 'passed': 620, 'error': 20}

Process finished with exit code 0
